export default {
  category: '反馈',
  componentName: 'ElDialog',
  npm: {
    package: 'element-plus',
    version: '2.2.6',
    exportName: 'ElDialog',
    destructuring: true,
  },
  props: [
    {
      name: 'v-model',
      propType: 'string',
      title: 'v-model',
      setter: 'ExpressionSetter',
    },
    {
      name: 'width',
      propType: {
        type: 'oneOfType',
        value: ['string', 'number'],
      },
      title: '宽度',
      setter: false,
    },
    {
      name: 'center',
      propType: 'bool',
      title: '内容居中',
      setter: 'BoolSetter',
    },
    {
      name: 'customClass',
      propType: 'string',
      title: 'customClass',
      setter: 'StringSetter',
    },
    // {
    //   name: 'draggable',
    //   propType: 'bool',
    //   title: '弹窗可拖拽',
    //   setter: 'BoolSetter',
    // },
    {
      name: 'fullscreen',
      propType: 'bool',
      title: '是否全屏',
      setter: 'BoolSetter',
    },
    {
      name: 'showClose',
      propType: 'bool',
      title: '显示关闭按钮',
      setter: 'BoolSetter',
    },
    {
      name: 'title',
      propType: 'string',
      title: '标题',
      setter: 'StringSetter',
    },
    {
      name: 'appendToBody',
      propType: 'bool',
      title: 'appendToBody',
      setter: 'BoolSetter',
    },
    {
      name: 'beforeClose',
      propType: 'func',
      title: 'beforeClose',
      setter: false,
    },
    {
      name: 'destroyOnClose',
      propType: 'bool',
      title: '关闭销毁内容',
      setter: 'BoolSetter',
    },
    {
      name: 'closeOnClickModal',
      propType: 'bool',
      title: '点击遮罩关闭',
      setter: 'BoolSetter',
    },
    {
      name: 'closeOnPressEscape',
      propType: 'bool',
      title: 'ESC关闭',
      setter: 'BoolSetter',
    },
    {
      name: 'lockScroll',
      propType: 'bool',
      title: '滚动锁定',
      setter: 'BoolSetter',
    },
    {
      name: 'modal',
      propType: 'bool',
      title: '是否遮罩',
      setter: 'BoolSetter',
    },
    {
      name: 'openDelay',
      propType: 'number',
      title: 'openDelay',
      setter: false,
    },
    {
      name: 'closeDelay',
      propType: 'number',
      title: 'closeDelay',
      setter: false,
    },
    {
      name: 'top',
      propType: 'string',
      title: '距离顶部',
      setter: 'StringSetter',
    },
    {
      name: 'modalClass',
      propType: 'string',
      title: 'modalClass',
      setter: 'StringSetter',
    },
    {
      name: 'zIndex',
      propType: 'number',
      title: 'zIndex',
      setter: false,
    },
    {
      name: 'footer',
      title: { label: '底部操作', tip: 'Dialog 按钮操作区的内容' },
      propType: { type: 'oneOfType', value: ['node'] },
    },
  ],
  configure: {
    supports: {
      style: true,
      loop: true,
      events: [
        'onOpen',
        'onOpened',
        'onClose',
        'onClosed',
        'onUpdate:modelvalue',
        'onOpenautofocus',
        'onCloseautofocus',
      ],
    },
    component: {
      isContainer: true,
      isModal: true,
    },
  },
  keywords: 'ElDialog',
};
